name: Build and Deploy Flask App to ECS

# on:
#   push:
#     branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t flask-app ./app
          DATE_TAG=$(date +%F)
          docker tag flask-app:latest ${{ secrets.ECR_REPO_URL }}:$DATE_TAG
          docker tag flask-app:latest ${{ secrets.ECR_REPO_URL }}:latest

      - name: Push Docker image to ECR
        run: |
          DATE_TAG=$(date +%F)
            docker push ${{ secrets.ECR_REPO_URL }}:$DATE_TAG
            docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Deploy to ECS Fargate
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment
